version: "2.4"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
      MYSQL_DATABASE: "db_pokebattle"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./deploy/local/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
      - "3307:3306"

  # hex-pokebattle:
  #   build:
  #     context: .
  #     dockerfile: build/package/lambda-mysql/Dockerfile
  #   environment:
  #     DB_DRIVER: "mysql"
  #     DB_SOURCE_NAME: "root:root@tcp(db:3306)/test"
  #     MYSQL_HOST: "db"
  #     MYSQL_PASSWORD: "root"
  #     MYSQL_USER: "root"
  #     MYSQL_PORT: "3306"
  #     MYSQL_DB: "test"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - 9186:9186
