version: "3.7"

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,lambda
      - AWS_DEFAULT_REGION=eu-west-1
      - SEED_POKEMON
    volumes:
      - './deploy/local/init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh'
      - './deploy/local/enemy-batch-write-items.json:/var/enemy-batch-write-items.json'
      - './deploy/local/partner-batch-write-items.json:/var/partner-batch-write-items.json'

  hex-pokebattle:
    build:
      dockerfile: ./build/package/lambda/Dockerfile
    depends_on:
      - localstack
    ports:
      - 9186:9186
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION
      - AWS_SECRET_ACCESS_KEY
      - DDB_TABLE_BATTLE_NAME=Battles
      - DDB_TABLE_GAME_NAME=Games
      - DDB_TABLE_POKEMON_NAME=Pokemons
      - IS_SERVER_MODE=true
