AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Hex Pokebattle
  SAM Template for hex-pokebattle

Mappings:
  Dev:
    StageName:
      Value: Dev

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    AllowedValues:
      - Dev
      - Prod
  InfraStackName:
    Type: String
    Description: Infras stack name for this app
  ImageUri:
    Type: String
    Description: Docker image URI for hex-pokebattle

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:


  HexPokebattleAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap [!Ref Environment, StageName, Value]

  EntrypointFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      Architectures:
        - x86_64
      Events:
        RootEndpoint:
          Properties:
            Method: any
            Path: /
            RestApiId: !Ref HexPokebattleAPI
          Type: Api
        EverythingElse:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref HexPokebattleAPI
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue: !Sub "${InfraStackName}:BattleTableName"
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue: !Sub "${InfraStackName}:GameTableName"
        - DynamoDBCrudPolicy:
            TableName:
              Fn::ImportValue: !Sub "${InfraStackName}:PokemonTableName"

      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DDB_BATTLE_TABLE:
            Fn::ImportValue: !Sub "${InfraStackName}:BattleTableName"
          DDB_GAME_TABLE:
            Fn::ImportValue: !Sub "${InfraStackName}:GameTableName"
          DDB_POKEMON_TABLE:
            Fn::ImportValue: !Sub "${InfraStackName}:PokemonTableName"
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ../..
      Dockerfile: ./build/package/lambda/Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HexPokebattleAPI:
    Description: "API Gateway endpoint URL for Prod environment for Entrypoint Function"
    Value: !Sub "https://${HexPokebattleAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
