version: "2.4"

services:
  server:
    build:
      context: ../../../../
      dockerfile: ./build/package/server/Dockerfile
    volumes:
      - ../../../../internal:/go/src/github.com/Haraj-backend/hex-monscape/internal
      - ../../../../cmd/server:/go/src/github.com/Haraj-backend/hex-monscape/cmd/server
      - ../../../../tmp/go/pkg:/go/pkg
    ports:
      - 9186:9186
