version: "2.4"

services:
  localstack:
    image: localstack/localstack:0.14
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=eu-west-1
      - DONT_SEED_POKEMON=false
    healthcheck:
      test: "/wait-localstack.sh -s dynamodb -h localhost:4566 -w 0 -r 1"
    entrypoint: bash -c "apt-get install jq -y; docker-entrypoint.sh"
    volumes:
      - ../shared/wait-localstack.sh:/wait-localstack.sh
      - ../shared/ddb-create-tables.sh:/docker-entrypoint-initaws.d/1.sh
      - ./ddb-write-data.sh:/docker-entrypoint-initaws.d/2.sh
      - ./ddb-data.json:/ddb-data.json
    logging:
      driver: none

  mysql:
    image: bitnami/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
      MYSQL_DATABASE: "db_pokebattle"
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 20s
      retries: 10
    volumes:
      - ../shared/mysql-schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql-data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "3307:3306"
    logging:
      driver: none

  rest-mem:
    build:
      context: ../../../
      dockerfile: ./build/package/rest-mem/Dockerfile
    volumes:
      - ../../../internal:/go/src/github.com/Haraj-backend/hex-pokebattle/internal
      - ../../../cmd/rest-mem:/go/src/github.com/Haraj-backend/hex-pokebattle/cmd/rest-mem
      - ../../../build/package/rest-mem/.air.toml:/go/src/github.com/Haraj-backend/hex-pokebattle/build/package/rest-mem/.air.toml
    ports:
      - 9185:9186
    environment:
      - SERVICE_NAME=rest-mem
      - PORT=9186

  rest-ddb:
    build:
      context: ../../../
      dockerfile: ./build/package/rest-ddb/Dockerfile.local
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - 9186:9186
    volumes:
      - ../../../internal:/go/src/github.com/Haraj-backend/hex-pokebattle/internal
      - ../../../cmd/rest-ddb:/go/src/github.com/Haraj-backend/hex-pokebattle/cmd/rest-ddb
      - ../../../build/package/rest-ddb/.air.toml:/go/src/github.com/Haraj-backend/hex-pokebattle/build/package/rest-ddb/.air.toml
    environment:
      - AWS_ACCESS_KEY_ID=awslocal
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=awslocal
      - LOCAL_DEPLOYMENT_ENABLED=true
      - LOCAL_DEPLOYMENT_ENDPOINT=http://localstack:4566
      - LOCAL_DEPLOYMENT_PORT=9186
      - DDB_BATTLE_TABLE=Battles
      - DDB_GAME_TABLE=Games
      - DDB_POKEMON_TABLE=Pokemons

  rest-mysql:
    build:
      context: ../../../
      dockerfile: ./build/package/rest-mysql/Dockerfile.local
    environment:
      PORT: 9186
      SERVER_DEPLOYMENT: "true"
      SERVICE_NAME: rest-mysql
      SQL_DSN: "root:test1234@tcp(mysql:3306)/db_pokebattle"
    volumes:
      - ../../../internal:/go/src/github.com/Haraj-backend/hex-pokebattle/internal
      - ../../../cmd/rest-mysql:/go/src/github.com/Haraj-backend/hex-pokebattle/cmd/rest-mysql
      - ../../../build/package/rest-mysql/.air.toml:/go/src/github.com/Haraj-backend/hex-pokebattle/build/package/rest-mysql/.air.toml
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 9187:9186
