version: "2.4"

services:
  localstack:
    image: localstack/localstack:0.14
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=eu-west-1
      - DONT_SEED_POKEMON=false
    healthcheck:
      test: "/wait-localstack.sh -s dynamodb -h localhost:4566 -w 0 -r 1"
    entrypoint: bash -c "apt-get install jq -y; docker-entrypoint.sh"
    volumes:
      - ../shared/wait-localstack.sh:/wait-localstack.sh
      - ../shared/ddb-create-tables.sh:/docker-entrypoint-initaws.d/1.sh
      - ./ddb-write-data.sh:/docker-entrypoint-initaws.d/2.sh
      - ./ddb-data.json:/ddb-data.json
    logging:
      driver: none

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
      MYSQL_DATABASE: "db_pokebattle"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ../shared/mysql-schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql-data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "3307:3306"
    logging:
      driver: none

  rest-http-mem:
    build:
      context: ../../../
      dockerfile: ./build/package/rest-http-mem/Dockerfile
    ports:
      - 9185:9186

  rest-lambda-ddb:
    build:
      context: ../../../
      dockerfile: ./build/package/rest-lambda-ddb/Dockerfile.local
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - 9186:9186
    volumes:
      - '../../../cmd/rest-lambda-ddb/config.yml:/config.yml'
    environment:
      - AWS_ACCESS_KEY_ID=awslocal
      - AWS_REGION=eu-west-1
      - AWS_SECRET_ACCESS_KEY=awslocal

  rest-lambda-mysql:
    build:
      context: ../../../
      dockerfile: ./build/package/rest-lambda-mysql/Dockerfile.local
    environment:
      SERVER_DEPLOYMENT: "true"
      SQL_DSN: "root:test1234@tcp(mysql:3306)/db_pokebattle"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 9187:9186
