name: Deploy to Dev environment

on:
  push:
    branches: [master]

jobs:
  run-test:
    uses: ./.github/workflows/test_services.yml
    name: Run tests before deploy
    with:
      checkout-ref: ${{ github.sha }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      SOLUTIONS_TEAM_SLACK_WEBHOOK: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}

  deploy-dev:
    name: Deploy to Dev
    needs: run-test
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1
    steps:
      - name: Checkout Current Commit
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.DEV_AWS_DEPLOY_ROLE_ARN }}
          role-duration-seconds: 3600
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy related infras to Dev
        run: make deploy-infras-dev

      - name: Deploy to Dev
        run: make deploy-dev

      - name: Notify To Slack
        uses: lazy-actions/slatify@v3.0.0
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "*Hex-Pokebattle ${{ github.job }}*"
          mention: "here"
          mention_if: "failure"
          channel: "#solutions-team-ci-cd"
          icon_emoji: ":haraaj:"
          username: "ci/cd-reporter"
          url: ${{ secrets.SOLUTIONS_TEAM_SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
